<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content=""/>
<meta property="og:description" content=""/>
<meta property="og:image" content="">
<meta property="og:url" content="">
<title></title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<?= $this->partial('/common/setjs.phtml', $this) ?>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/common.css">
<?= $this->partial('/common/setcss.phtml', $this) ?>
</head>
<body>
<?= $this->partial('/common/navbar.phtml', $this) ?>
