      <ul class="nav navbar-nav menu">
        <?php foreach ($this->menu as $menuitem) { ?>
        <?php if (isset($menuitem->submenu)) { ?>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $menuitem->name ?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <?php foreach($menuitem->submenu as $submenuitem) { ?>
            <li><a href="#<?= $menuitem->id . '/' . $submenuitem->id ?>"><?= $submenuitem->name ?></a></li>
            <?php } ?>
            <!-- <li class="divider"></li> -->
          </ul>
        </li>
        <?php } else { ?>
        <li><a href="#<?= $menuitem->id ?>"><?= $menuitem->name ?></a></li>
        <?php } ?>
        <?php } ?>
      </ul>
